server:
  port: 8080

spring:
  profiles:
    active: dev
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    validationQuery: select 1 from dual

# myBatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
