server:
  port: 8080

spring:
  profiles:
    active: dev
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    validationQuery: select 1 from dual

# myBatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml


# if the application need to open transaction
# 1. the @EnableTransactionManagement must be set on the main class
# 2. set the lcn.transaction.enable to true
# 3. set the lcn.advisorExpression
# 4. the application must have data source, such as druid, HikariCP etc.
app:
  transaction:
    enable: true
    advisor-expression: "execution(* com.mall.service.impl..*.*(..))"
