# 日志路径
logging:
  file:
    path: E:\application\mall

spring:
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/mall-db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Li*123456
    # druid 连接池
    druid:
      initial-size: 10
      min-idle: 30
      max-active: 100
      max-wait: 3000
      remove-abandoned-timeout: 180
