# 日志路径
logging:
  file:
    path: D:\application\mall

spring:
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/mall-db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    # druid 连接池
    druid:
      initial-size: 10
      min-idle: 30
      max-active: 100
      max-wait: 3000
      remove-abandoned-timeout: 180
  # redis 集群
  redis:
    jedis:
      pool:
        max-active: 1000
        max-idle: 10
        max-wait: -1
        min-idle:  5
    cluster:
      nodes:
        - 192.168.3.123:9001
        - 192.168.3.123:9002
        - 192.168.3.123:9003
        - 192.168.3.123:9004
        - 192.168.3.123:9005
        - 192.168.3.123:9006
      max-redirects: 3
    timeout: 500




